image: node

before_script:
  - yarn install

cache:
  paths:
    - node_modules/
    - .yarn/

pages:
  script:
    - yarn generate
    - mv dist public
  artifacts:
    paths:
      - dist
  only:
    - master